### Day 4

In [3]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8]])
a.reshape(1,8)
a.reshape(8,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [1]:
import pandas as pd

lst1 = [1,2,3,4,5,6]
lst2 = [7,8,9,10,11,12]

#pdSeries
print("pdSries")
s1=pd.Series(lst1)
print(s1)

#pdDataFrame
print("pdDataFrame","A")
df = pd.DataFrame(lst1)
print(df)

#pdconcat
print("pdconcat")
s2=pd.Series(lst2)
s3=pd.concat([s1,s2],axis=1)
print(s3)

#loc-Selecting a single row
print("loc")
temp=df.loc[2]
print(temp)

#iloc
print("iloc")
temp1=df.loc[1]
print(temp1)



pdSries
0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
pdDataFrame A
   0
0  1
1  2
2  3
3  4
4  5
5  6
pdconcat
   0   1
0  1   7
1  2   8
2  3   9
3  4  10
4  5  11
5  6  12
loc
0    3
Name: 2, dtype: int64
iloc
0    2
Name: 1, dtype: int64


In [2]:
import numpy as np
lst=[1,2]

#nparray
a1=np.array(lst)
print(a1)

#shape
print(a1.shape)

#ndim
print(a1.ndim)

#reshape
a2=a1.reshape(-1,1)
print(a2)

#copy
a3=a1.copy()
print(a3)


[1 2]
(2,)
1
[[1]
 [2]]
[1 2]


In [11]:
#4
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
df=pd.read_csv(r'data\sales_data.csv')
df
 
    


ORDERNUMBER  QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER    SALES  \
0           10107               30      95.70                2  2871.00   
1           10121               34      81.35                5  2765.90   
2           10134               41      94.74                2  3884.34   
3           10145               45      83.26                6  3746.70   
4           10159               49     100.00               14  5205.27   
...           ...              ...        ...              ...      ...   
2818        10350               20     100.00               15  2244.40   
2819        10373               29     100.00                1  3978.51   
2820        10386               43     100.00                4  5417.57   
2821        10397               34      62.24                1  2116.16   
2822        10414               47      65.52                9  3079.44   

             ORDERDATE    STATUS  QTR_ID  MONTH_ID  YEAR_ID  ...  \
0       2/24/2003 0:00   Shipped       1         2     2003  ...   
1     05-07-2003 00:00   Shipped       2         5     2003  ...   
2     07-01-2003 00:00   Shipped       3         7     2003  ...   
3       8/25/2003 0:00   Shipped       3         8     2003  ...   
4     10-10-2003 00:00   Shipped       4        10     2003  ...   
...                ...       ...     ...       ...      ...  ...   
2818  12-02-2004 00:00   Shipped       4        12     2004  ...   
2819    1/31/2005 0:00   Shipped       1         1     2005  ...   
2820  03-01-2005 00:00  Resolved       1         3     2005  ...   
2821    3/28/2005 0:00   Shipped       1         3     2005  ...   
2822  05-06-2005 00:00   On Hold       2         5     2005  ...   

                       ADDRESSLINE1  ADDRESSLINE2           CITY STATE  \
0           897 Long Airport Avenue           NaN            NYC    NY   
1                59 rue de l'Abbaye           NaN          Reims   NaN   
2     27 rue du Colonel Pierre Avia           NaN          Paris   NaN   
3                78934 Hillside Dr.           NaN       Pasadena    CA   
4                   7734 Strong St.           NaN  San Francisco    CA   
...                             ...           ...            ...   ...   
2818             C/ Moralzarzal, 86           NaN         Madrid   NaN   
2819                    Torikatu 38           NaN           Oulu   NaN   
2820             C/ Moralzarzal, 86           NaN         Madrid   NaN   
2821          1 rue Alsace-Lorraine           NaN       Toulouse   NaN   
2822             8616 Spinnaker Dr.           NaN         Boston    MA   

     POSTALCODE  COUNTRY TERRITORY CONTACTLASTNAME CONTACTFIRSTNAME DEALSIZE  
0         10022      USA       NaN              Yu             Kwai    Small  
1         51100   France      EMEA         Henriot             Paul    Small  
2         75508   France      EMEA        Da Cunha           Daniel   Medium  
3         90003      USA       NaN           Young            Julie   Medium  
4           NaN      USA       NaN           Brown            Julie   Medium  
...         ...      ...       ...             ...              ...      ...  
2818      28034    Spain      EMEA          Freyre            Diego    Small  
2819      90110  Finland      EMEA       Koskitalo           Pirkko   Medium  
2820      28034    Spain      EMEA          Freyre            Diego   Medium  
2821      31000   France      EMEA          Roulet          Annette    Small  
2822      51003      USA       NaN         Yoshido             Juri   Medium  

[2823 rows x 25 columns]

In [12]:
df=df[['QUANTITYORDERED','PRICEEACH','SALES',]]
df=df.dropna()
df


QUANTITYORDERED  PRICEEACH    SALES
0                  30      95.70  2871.00
1                  34      81.35  2765.90
2                  41      94.74  3884.34
3                  45      83.26  3746.70
4                  49     100.00  5205.27
...               ...        ...      ...
2818               20     100.00  2244.40
2819               29     100.00  3978.51
2820               43     100.00  5417.57
2821               34      62.24  2116.16
2822               47      65.52  3079.44

[2823 rows x 3 columns]

In [14]:
X=df[['QUANTITYORDERED','PRICEEACH']]
y=df[['SALES']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)
model =LinearRegression()
model.fit(X_train,y_train)
pd.to_pickle(model,"sales_model.pickle")
model1=pd.read_pickle(r"sales_model.pickle")
prd=model.predict(X_test)
prd


array([[1497.67646256],
       [2714.88648996],
       [4922.49709368],
       ...,
       [2808.41677841],
       [5426.99070144],
       [3759.50311227]])

In [15]:
y_pred = model.predict(X_test)
print('Coefficients: \n', model.coef_)
print("Mean squared error: %.2f" % np.mean((model.predict(X_test) - y_test) ** 2))
print('Variance score: %.2f' % model.score(X_test, y_test))


Coefficients: 
 [[100.89872155  59.9569006 ]]
Mean squared error: 1053434.22
Variance score: 0.71
